config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ____クライアント側devise_____
  devise_for :clients, skip: [:passwords,], controllers: {
    registrations: "client/registrations",
    sessions: 'client/sessions'
  }

  # ____モデル側devise_____
  devise_for :actors, skip: [:passwords,], controllers: {
    registrations: "actor/registrations",
    sessions: 'actor/sessions'
  }

  # ----管理者側devise------
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # ____クライアント側____
  namespace :client do
    resources :clients, only:[:show, :edit, :update, :favorite] do
      get :favorites, on: :collection
      get 'unsubscribe' => 'clients#unsubscribe'
      patch 'withdraw' => 'clients#withdraw'
    end
    resources :job_requests
  end

  # ____モデル側____
  scope module: :actor do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'login' => 'homes#login'
    resources :actors, only:[:index, :show, :edit, :update] do
    resource :favorites, only:[:create, :destroy]
    get 'unsubscribe' => 'actors#unsubscribe'
    patch 'withdraw' => 'actors#withdraw'
    end
    resources :job_requests, only:[:index]
    resources :clients, only:[:index]
    get 'inquiry' => 'inquiries#index'
    post 'inquiry/confirm' => 'inquiries#confirm'
    post 'inquiry/thanks' => 'inquiries#thanks'
  end

  # ------管理者側-------
  namespace :admin do
    get 'top' => 'homes#top'
    resources :actors, only:[:index, :show, :edit, :update]
    resources :clients, only:[:index, :show, :edit, :update]
  end
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites
  has_many :actors, through: :favorites
  has_many :job_requests

  attachment :image

  # 名前とメールアドレスのバリデーション
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }, allow_blank: true
end

app/controllers/actor/clients_controller.rb
class Actor::ClientsController < ApplicationController
  def index
    @clients = Client.all.page(params[:page]).per(16)
  end
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < ApplicationController
    before_action :authenticate_admin!

    def index
      @clients = Client.all.page(params[:page]).per(20)
    end

    def show
      @client = Client.find(params[:id])
    end

    def edit
      @client = Client.find(params[:id])
    end

    def update
      @client = Client.find(params[:id])
      if @client.update(client_params)
        redirect_to admin_client_path(@client.id)
      else
        render "edit"
      end
    end

    private

    def client_params
      params.require(:client).permit(:name, :email, :image, :body, :contact, :is_deleted)
    end

end

app/controllers/client/clients_controller.rb
class Client::ClientsController < ApplicationController
  before_action :authenticate_client!, except: [:show]
  before_action :set_client, only: [:show, :edit, :update]

  def show
    # viwes/client/job_request/の依頼者:の所で使用
    @job_request = @client.job_requests
  end

  def edit
    # ------ログインユーザーとidが一致してないとtopに戻すセキュリティー---
    if @client.id == current_client.id
      render "edit"
    else
      redirect_to root_path
    end
  end

  def update
    if @client.update(client_params)
      redirect_to client_client_path(@client.id)
    else
      render "edit"
    end
  end

  def favorites
    favorites = Favorite.where(client_id: current_client.id).pluck(:actor_id)
    @favorite_list = Actor.find(favorites)
  end
  
  #------- 退会機能------
  def unsubscribe
    @cient = current_client
  end

  def withdraw
    @client = current_client
    @client.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end
  # ------ここまで-------

  private

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:name, :image, :body, :contact, :is_deleted)
  end
end

app/controllers/client/confirmations_controller.rb
# frozen_string_literal: true

class Client::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/client/job_requests_controller.rb
class Client::JobRequestsController < ApplicationController
  before_action :authenticate_client!, except: [:show]
  before_action :set_jobrequest, only: [:show, :edit, :update, :destroy]

  def index
    @job_requests = current_client.job_requests.page(params[:page])
  end

  def show
  end

  def edit
    if @job_request.client.id == current_client.id
      render "edit"
    else
      redirect_to root_path
    end
  end

  def new
    @job_request = JobRequest.new
  end

  def create
    @job_request = JobRequest.new(job_request_params)
    @job_request.client_id = current_client.id
    if @job_request.save
      redirect_to client_job_requests_path
    else
      render "new"
    end
  end

  def update
    if @job_request.update(job_request_params)
      redirect_to client_job_request_path(@job_request)
    else
      render "edit"
    end
  end

  def destroy
    @job_request.destroy
    redirect_to client_job_requests_path
  end

  private

  def set_jobrequest
    @job_request = JobRequest.find(params[:id])
  end

  def job_request_params
    params.require(:job_request).permit(:title, :job_content, :recruitment_gender,
    :recruitment_stature, :recruitmebt_other, :money, :contact)
  end
end

app/controllers/client/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Client::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/client/passwords_controller.rb
# frozen_string_literal: true

class Client::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/client/registrations_controller.rb
# frozen_string_literal: true

class Client::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/client/sessions_controller.rb
# frozen_string_literal: true

class Client::SessionsController < Devise::SessionsController
  before_action :client_state, only:[:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  # ---------退会機能--------
  protected

  def client_state
    @client = Client.find_by(email: params[:client][:email])
    return if !@client
    if @client.valid_password?(params[:client][:password]) && @client.is_deleted
      redirect_to new_client_registration_path
    end
  end

end

app/controllers/client/unlocks_controller.rb
# frozen_string_literal: true

class Client::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/actor/clients_helper.rb
module Actor::ClientsHelper
end

app/helpers/admin/clients_helper.rb
module Admin::ClientsHelper
end

app/helpers/client/clients_helper.rb
module Client::ClientsHelper
end

app/helpers/client/favorites_helper.rb
module Client::FavoritesHelper
end

app/helpers/client/job_requests_helper.rb
module Client::JobRequestsHelper
end

app/helpers/client/searchs_helper.rb
module Client::SearchsHelper
end

app/views/admin/clients/edit.html.erb
<div class="container">
  <div class="r_client_text1 row d-flex align-items-center justify-content-center">
    <div class="r_client_text2 border col-lg-7 my-5 bg-white">
      <h1 class="py-1 mt-3 bg-dark text-white text-center"><strong>Client Edit</strong></h1>
        <div class="row">
          <div class="col-md my-4">
            <%= form_with model: @client, url: admin_client_path(@client.id), local:true do |f| %>
              <form>
                <div class="form-group">
                  <label>名前（クライアント名）:</label><br/>
                  <%= f.text_field :name, class:"w-50" %>
                </div>
                <div class="form-group">
                  <label>登録メールアドレス:</label><br/>
                  <%= f.text_field :email, class:"w-50" %>
                </div>
                <div class="form-group">
                  <label>プロフィール写真:</label><br/>
                  <%= f.attachment_field :image, class:"mb-1" %><br/>
                  <!---------プレビュー機能----->
                  <img id="preview" style="width:40%;">
                  <!----------ここまで---------->
                </div>
                <div class="form-group">
                  <label>自己紹介:</label><br/>
                  <%= f.text_area :body, class: "form-control pb-4" %>
                </div>
                <div class="form-group">
                  <label>連絡先:</label><br/>
                  <%= f.text_field :contact, class:"w-50" %>
                </div>
                <div class="form-group">
                  <label>会員ステータス：</label><br/>
                  <%= f.radio_button :is_deleted, false %>
                  <%= f.label :is_deleted, "有効" %>
                  <%= f.radio_button :is_deleted, true %>
                  <%= f.label :is_deleted, "退会" %>
                </div>
                <div class="text-center mt-4">
                  <%= f.submit "保存", class: "btn btn-secondary btn-lg" %>
                </div>
              </form>
            <% end %>
          </div>
        </div>
    </div>
  </div>
</div>

<!---------プレビュー機能（上記も記載あり）----------->
<script>
  $('#client_image').on('change', function (e) {
    var reader = new FileReader();
    reader.onload = function (e) {
        $("#preview").attr('src', e.target.result);
    }
    reader.readAsDataURL(e.target.files[0]);
});
</script>

app/views/admin/clients/index.html.erb
<h1 class="py-3 bg-dark text-white text-center"><strong>CLIENT</strong></h1>

  <div class="container pb-5">
    <div class="row text-center mt-5 bg-white">
        <table class="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>名前</th>
              <th class="ml-2">登録日</th>
              <th>会員ステータス</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @clients.each do |client| %>
              <tr>
                <td><%= client.id %></td>
                <td><%= client.name %></td>
                <td><%= client.created_at.strftime("%Y/%m/%d") %></td>
                <% if client.is_deleted == true %>
                  <td class="text-danger">退会</td>
                <% else %>
                  <td class="text-success">有効</td>
                <% end %>
                <td class="text-right"><%= link_to "詳細", admin_client_path(client), class: "btn btn-secondary" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

 <!----kaminari----->
<div class="d-flex align-items-center justify-content-center">
<%= paginate @clients %>
</div>

app/views/admin/clients/show.html.erb
<div class="container py-5">
    <div class="row bg-white shadow-lg rounded border border-secondary mx-5">
      <div class="col-11">
        <h1 class="my-3 ml-2"><strong><%= @client.name %></strong></h1>
         <table class='table ml-3'>
            <tr>
              <th>登録メールアドレス：</th>
              <th><%= @client.email %></th>
            </tr>
            <tr>
              <th class="pr-5">自己紹介：</th>
              <th><%=simple_format(h(@client.body)) %></th>
            </tr>
            <tr>
              <th>連絡先：</th>
              <th><%= @client.contact %></th>
            </tr>
            <tr>
              <th>会員ステータス：</th>
              <% if @client.is_deleted == true %>
                <th class="text-danger">退会</th>
              <% else %>
                <th class="text-success">有効</th>
              <% end %>
            </tr>
         </table>
         <div class="row d-flex align-items-center justify-content-center my-3">
            <% if admin_signed_in? %>
              <%= link_to "編集", edit_admin_client_path(@client), class: "btn btn-secondary btn-lg" %>
            <% end %>
         </div>
      </div>
    </div>
  </div>