config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ____クライアント側devise_____
  devise_for :clients, skip: [:passwords,], controllers: {
    registrations: "client/registrations",
    sessions: 'client/sessions'
  }

  # ____モデル側devise_____
  devise_for :actors, skip: [:passwords,], controllers: {
    registrations: "actor/registrations",
    sessions: 'actor/sessions'
  }

  # ----管理者側devise------
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # ____クライアント側____
  namespace :client do
    resources :clients, only:[:show, :edit, :update, :favorite] do
      get :favorites, on: :collection
      get 'unsubscribe' => 'clients#unsubscribe'
      patch 'withdraw' => 'clients#withdraw'
    end
    resources :job_requests
  end

  # ____モデル側____
  scope module: :actor do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'login' => 'homes#login'
    resources :actors, only:[:index, :show, :edit, :update] do
    resource :favorites, only:[:create, :destroy]
    get 'unsubscribe' => 'actors#unsubscribe'
    patch 'withdraw' => 'actors#withdraw'
    end
    resources :job_requests, only:[:index]
    resources :clients, only:[:index]
    get 'inquiry' => 'inquiries#index'
    post 'inquiry/confirm' => 'inquiries#confirm'
    post 'inquiry/thanks' => 'inquiries#thanks'
  end

  # ------管理者側-------
  namespace :admin do
    get 'top' => 'homes#top'
    resources :actors, only:[:index, :show, :edit, :update]
    resources :clients, only:[:index, :show, :edit, :update]
  end
end

app/models/actor.rb
class Actor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  attachment :image

  # 名前とメールアドレスのバリデーション
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }, allow_blank: true

  # ------お気に入り機能-----------
  def favorited_by?(client)
    favorites.where(client_id: client.id).exists?
  end

  # -----トラッキング機能（PV数）------
  is_impressionable counter_cache: true
end

app/controllers/actor/actors_controller.rb
class Actor::ActorsController < ApplicationController
  before_action :authenticate_actor!, except: [:index, :show]
  before_action :set_actor, only: [:show, :edit, :update]
  # 更新しても閲覧数がカウントしないように設定したため下記２つ「, unique: [:ip_address]」を消すと閲覧数は上がる
  impressionist :actions => [:show], unique: [:ip_address]

  def index
    @q = Actor.ransack(params[:q])
    @actors = @q.result(distinct: true).page(params[:page]).per(16)
  end

  def show
    # ----トラッキング機能（1つのIPアドレスで1PVあがる）----
    impressionist(@actor, nil, unique: [:ip_address])
  end

  def edit
    # ------ログインユーザーとidが一致してないとtopに戻すセキュリティー---
    if @actor.id == current_actor.id
      render "edit"
    else
      redirect_to root_path
    end
  end

  def update
    if @actor.update(actor_params)
      redirect_to actor_path(@actor.id)
    else
      render "edit"
    end
  end

  # ----------退会機能----------
  def unsubscribe
    @actor = current_actor
  end

  def withdraw
    @actor = current_actor
    @actor.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end
  # ---------ここまで-----------

  private

  def set_actor
    @actor = Actor.find(params[:id])
  end

  def actor_params
    params.require(:actor).permit(:name, :image, :born_year, :born_month, :born_day, :age, :body, :career,
    :contact, :stature, :gender, :instagram_rink, :twitter_rink, :tiktok_rink, :others_rink, :is_deleted, :string)
  end
end

app/controllers/actor/clients_controller.rb
class Actor::ClientsController < ApplicationController
  def index
    @clients = Client.all.page(params[:page]).per(16)
  end
end

app/controllers/actor/confirmations_controller.rb
# frozen_string_literal: true

class Actor::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/actor/favorites_controller.rb
class Actor::FavoritesController < ApplicationController
  before_action :authenticate_client!, except: [:create, :destroy]

  def create
    @actor = Actor.find(params[:actor_id])
    favorite = current_client.favorites.new(actor_id: @actor.id)
    favorite.save
  end

  def destroy
    @actor = Actor.find(params[:actor_id])
    favorite = current_client.favorites.find_by(actor_id: @actor.id)
    favorite.destroy
  end
end

app/controllers/actor/homes_controller.rb
class Actor::HomesController < ApplicationController
  def top
    # ---トラッキング機能で閲覧数の多い順---
    @ranks = Actor.order(impressions_count: 'DESC').limit(4)
    # -------新規作成順--------
    @actors = Actor.order(created_at: :desc).limit(4)
  end

  def about
  end
  
  def login
  end
end

app/controllers/actor/inquiries_controller.rb
class Actor::InquiriesController < ApplicationController
  def index
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))

    if @inquiry.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def thanks
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    InquiryMailer.received_email(@inquiry).deliver
    render :action => 'thanks'
  end
end

app/controllers/actor/job_requests_controller.rb
class Actor::JobRequestsController < ApplicationController
  def index
    @job_requests = JobRequest.all.order(created_at: :desc).page(params[:page]).per(8)
  end
end

app/controllers/actor/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Actor::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/actor/passwords_controller.rb
# frozen_string_literal: true

class Actor::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/actor/registrations_controller.rb
# frozen_string_literal: true

class Actor::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/actor/sessions_controller.rb
# frozen_string_literal: true

class Actor::SessionsController < Devise::SessionsController
  before_action :actor_state, only:[:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  # ---------退会機能---------
  protected

  def actor_state
    @actor = Actor.find_by(email: params[:actor][:email])
    return if !@actor
    if @actor.valid_password?(params[:actor][:password]) && @actor.is_deleted
      redirect_to new_actor_registration_path, notice: 'このユーザーは退会されているためご利用できません。新規登録を行ってください'
    end
  end

end

app/controllers/actor/unlocks_controller.rb
# frozen_string_literal: true

class Actor::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/actors_controller.rb
class Admin::ActorsController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_actor, only: [:show, :edit, :update]

    def index
      @actors = Actor.all.page(params[:page]).per(20)
    end

    def show
    end

    def edit
    end

    def update
      if @actor.update(actor_params)
        redirect_to admin_actor_path(@actor.id)
      else
        render "edit"
      end
    end

    private

    def set_actor
      @actor = Actor.find(params[:id])
    end

    def actor_params
      params.require(:actor).permit(:name, :email, :image, :born_year, :born_month, :born_day, :age, :body, :career,
      :contact, :stature, :gender, :instagram_rink, :twitter_rink, :tiktok_rink, :others_rink, :is_deleted)
    end

end

app/helpers/actor/actors_helper.rb
module Actor::ActorsHelper
end

app/helpers/actor/clients_helper.rb
module Actor::ClientsHelper
end

app/helpers/actor/homes_helper.rb
module Actor::HomesHelper
end

app/helpers/actor/inquiries_helper.rb
module Actor::InquiriesHelper
end

app/helpers/actor/job_requests_helper.rb
module Actor::JobRequestsHelper
end

app/helpers/actor/searchs_helper.rb
module Actor::SearchsHelper
end

app/views/admin/actors/edit.html.erb
<div class="container">
    <div class="row d-flex align-items-center justify-content-center">
        <div class="border col-lg-7 my-5 bg-white">
            <h2 class="my-3 text-center"><label class="actor-label py-1 px-3" >Model Edit</label></h2>
            <div class="row">
                <div class="col-md">
                    <%= form_with model: @actor, url: admin_actor_path(@actor), local:true do |f| %>
                            <form>
                                <div class="form-group">
                                    <label>名前（モデル名）:<span class="text-danger">（必須）</span></label><br/>
                                    <%= f.text_field :name %>
                                </div>
                                <div class="form-group">
                                    <label>登録メールアドレス:<span class="text-danger">（必須）</span></label><br/>
                                    <%= f.text_field :email %>
                                </div>
                                <div class="form-group">
                                    <label>My写真:</label><br/>
                                    <%= f.attachment_field :image, class:"mb-1"%><br/>
                                    <!---------プレビュー機能----->
                                    <img id="preview" style="width:40%;">
                                    <!----------ここまで---------->
                                </div>
                                <div class="form-group">
                                    <label>生年月日:</label><br/>
                                    <%= f.text_field :born_year, size: "7x7" %> 年 <%= f.text_field :born_month, size: "7x7" %> 月 <%= f.text_field :born_day, size: "7x7" %> 日
                                </div>
                                <div class="form-group">
                                    <label>年齢:</label><br/>
                                    <%= f.text_field :age, size: "6x6" %> 歳
                                </div>
                                <div class="form-group">
                                    <label>性別:<span class="text-danger">（必須）</span></label><br/>
                                    <%= f.radio_button :gender, true %>
                                    <%= f.label :gender, "女性" %>：
                                    <%= f.radio_button :gender, false %>
                                    <%= f.label :gender, "男性" %>
                                </div>
                                <div class="form-group">
                                    <label>身長:</label><br/>
                                    <%= f.text_field :stature, size: "7x7" %> cm
                                </div>
                                <div class="form-group">
                                    <label>自己PR:</label><br/>
                                    <%= f.text_area :body, class: "form-control" %>
                                </div>
                                <div class="form-group">
                                    <label>出演経歴:</label><br/>
                                    <%= f.text_area :career, class: "form-control" %>
                                </div>
                                 <div class="form-group">
                                    <label>連絡先:</label><br/>
                                    <%= f.text_field :contact, class: "form-control", placeholder:"例 : SNSアカウントにご連絡ください。" %>
                                </div>
                                <div class="form-group">
                                    <label>Instagramアカウント名:</label><br/>
                                    <%= f.text_field :instagram_rink, class: "form-control", placeholder:"例 : mode_connection" %>
                                </div>
                                <div class="form-group">
                                    <label>Twitterアカウント名:</label><br/>
                                    <%= f.text_field :twitter_rink, class: "form-control", placeholder:"例 : mode_connection" %>
                                </div>
                                <div class="form-group">
                                    <label>TikTokアカウント名:</label><br/>
                                    <%= f.text_field :tiktok_rink, class: "form-control", placeholder:"例 : @mode_connection" %>
                                </div>
                                <div class="form-group">
                                    <label>その他リンク先:</label><br/>
                                    <%= f.text_field :others_rink, class: "form-control", placeholder:"URLをお貼りください。" %>
                                </div>
                                <div class="form-group">
                                    <label>会員ステータス：</label><br/>
                                    <%= f.radio_button :is_deleted, false %>
                                    <%= f.label :is_deleted, "有効" %>
                                    <%= f.radio_button :is_deleted, true %>
                                    <%= f.label :is_deleted, "退会" %>
                                </div>
                                <div class="text-center pb-3">
                                    <%= f.submit "保存", class: "btn btn-secondary btn-lg" %>
                                </div>
                            </form>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>


<!---------プレビュー機能（上記も記載あり）----------->
<script>
  $('#actor_image').on('change', function (e) {
    var reader = new FileReader();
    reader.onload = function (e) {
        $("#preview").attr('src', e.target.result);
    }
    reader.readAsDataURL(e.target.files[0]);
});
</script>

app/views/admin/actors/index.html.erb
<h1 class="py-3 bg-dark text-white text-center"><strong>MODEL</strong></h1>

  <div class="container pb-5">
    <div class="row text-center mt-5 bg-white">
      <table class="table">
        <thead>
          <tr>
            <th>ID</th>
            <th>名前</th>
            <th class="ml-2">登録日</th>
            <th>会員ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @actors.each do |actor| %>
            <tr>
                <td><%= actor.id %></td>
                <td><%= actor.name %></td>
                <td><%= actor.created_at.strftime("%Y/%m/%d") %></td>
              <% if actor.is_deleted == true %>
                <td class="text-danger">退会</td>
              <% else %>
                <td class="text-success">有効</td>
              <% end %>
                <td class="text-right"><%= link_to "詳細", admin_actor_path(actor), class: "btn btn-secondary" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

 <!----kaminari----->
<div class="d-flex align-items-center justify-content-center">
<%= paginate @actors %>
</div>

app/views/admin/actors/show.html.erb
 <div class="container py-5">
    <div class="row bg-white shadow-lg rounded border border-secondary mx-5">
      <div class="col-11">
        <h1 class="my-3 ml-2"><strong><%= @actor.name %></strong></h1>
         <table class='table ml-3'>
           <tr>
              <th class="mr-5">ID：</th>
      	      <th><%= @actor.id %></th>
            </tr>
            <tr>
              <th class="mr-5">登録メールアドレス：</th>
      	      <th><%= @actor.email %></th>
            </tr>
            <tr>
              <th class="mr-5">生年月日：</th>
      	      <th><%= @actor.born_year %> 年 <%= @actor.born_month%> 月 <%= @actor.born_day %> 日</th>
            </tr>
            <tr>
              <th>年齢：</th>
              <th><%= @actor.age %> 歳</th>
            </tr>
            <tr>
              <th>性別：</th>
              <% if @actor.gender == true %>
                  <th>女性</th>
              <% else %>
                  <th>男性</th>
              <% end %>
            </tr>
            <tr>
              <th>身長：</th>
              <th><%= @actor.stature %> cm</th>
            </tr>
            <tr>
              <th>自己PR：</th>
              <th><%= simple_format(h(@actor.body)) %></th>
            </tr>
            <tr>
              <th>出演経歴：</th>
              <th><%= simple_format(h(@actor.career)) %></th>
            </tr>
            <tr>
              <th>連絡先：</th>
              <th><%= @actor.contact %></th>
            </tr>
            <tr>
              <th>会員ステータス：</th>
              <% if @actor.is_deleted == true %>
                <th class="text-danger">退会</th>
              <% else %>
                <th class="text-success">有効</th>
              <% end %>
            </tr>
         </table>
         <div class="row d-flex align-items-center justify-content-center my-3">
            <% if admin_signed_in? %>
                <%= link_to "編集", edit_admin_actor_path(@actor), class: "btn btn-secondary btn-lg" %>
            <% end %>
         </div>
      </div>
    </div>
  </div>